### ISSUE TITLE
Handle TypeError 

### ISSUE THREAD

**Issue by OrionRiitters** [OrionRiitters/path_finder#15]
When the event handler for find-path is passed a response with no trails, a TypeError is raised when it is trying to render a map.

**Comment by qaalib101** [comment]
I did not experience the issue. @OrionRiitters Is the api key saved in the app on your side?

**Comment by OrionRiitters** [comment]
I'm pretty sure the issue is that my code in search.js is just trying to read from an empty array. I forgot to do error-handling for the responses.

**Comment by qaalib101** [comment]
I believe it is solved however there is an issue with the getting the bucket list
